name: "Deploy Frontend to AWS EC2"

on:
  workflow_dispatch:
  push:

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}
      - name: Copy static frontend files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r frontend/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.DEPLOY_PATH }}
      - name: Restart web server (optional)
        run: |
          # Try restarting nginx, apache2, or httpd. If none found, skip.
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo systemctl restart nginx || sudo systemctl restart apache2 || sudo systemctl restart httpd || echo 'No known web server found, skipping restart.'"
      - name: Show deployed files
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "ls -l ${DEPLOY_PATH}"
