name: "Deploy to AWS EC2"

on:
  workflow_dispatch:
  push:

jobs:
  maven-build:
    uses: ./.github/workflows/maven.yml

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: maven-build
    if: ${{ success() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: traffic
          path: target/
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}
      - name: Copy artifact to EC2
        run: |
          scp -o StrictHostKeyChecking=no target/*.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.DEPLOY_PATH }}
      - name: Restart application on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "pkill -f 'java -jar' || true && nohup java -jar /app/ai-traffic-control-0.0.1-SNAPSHOT.jar > /app/app.log 2>&1 &"
